# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('subcategory', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('answer_text', models.CharField(max_length=255)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('used', models.BooleanField(default=False)),
                ('question_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Category')),
            ],
        ),
    ]
