# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_auto_20170513_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
    ]
