# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_remove_category_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('question_text', 'answer_text', 'question_category')]),
        ),
    ]
